[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'fcpg/vim-orbital'

#[[plugins]]
#repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'elianiva/icy.nvim'

[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'

[[plugins]]
repo = 'arzg/vim-substrata'

#[[plugins]]
#repo = 'ulwlu/abyss.vim'

[[plugins]]
repo = 'eskilop/NorthernLights.vim'

[[plugins]]
repo = 'pgdouyon/vim-alayas'

[[plugins]]
repo = 'cocopon/pgmnt.vim'

[[plugins]]
repo = 'kjssad/quantum.vim'

[[plugins]]
repo = 'projekt0n/github-nvim-theme'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
let g:tokyonight_style = 'night'
let g:tokyonight_enable_italic = 1
'''

[[plugin]]
repo = 'vim-scripts/reloaded.vim'

[[plugin]]
repo = 'vim-colors-tone'

[[plugin]]
repo = 'yasukotelin/shirotelin'

[[plugin]]
repo = 'rebelot/kanagawa.nvim'

[[plugin]]
repo = 'tiagovla/tokyodark.nvim'

[[plugin]]
repo = 'Badacadabra/vim-archery'

[[plugin]]
repo = 'tiagovla/tokyodark.nvim'

[[plugin]]
repo = 'catppuccin/nvim'

[[plugins]]
repo = 'wadackel/vim-dogrun'

# [[plugins]]
# repo = 'rakr/vim-two-firewatch'
# hook_add = '''
# let g:two_firewatch_italics=1
# '''

[[plugins]]
repo = 'liuchengxu/space-vim-dark'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'Badacadabra/vim-archery'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'vim-scripts/chlordane.vim'

[[plugins]]
repo = 'atelierbram/Base2Tone-vim'

[[plugins]]
repo = 'vim-scripts/darkbone.vim'

[[plugin]]
repo = 'hachy/eva01.vim'

[[plugin]]
repo = 'widatama/vim-phoenix'
