[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
colorscheme iceberg
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

#[[plugins]]
#repo = 'rhysd/accelerated-jk'
#hook_add = '''
#nmap j <Plug>(accelerated_jk_gj_position)
#nmap k <Plug>(accelerated_jk_gk_position)
#'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = '4513ECHO/vim-readme-viewer'
hook_add = '''
let g:readme_viewer#plugin_manager = 'dein.vim' 
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-skk/skkeleton',]
hook_add = '''
source $HOME/.config/nvim/lightlinerc.vim
'''

[[plugins]]
repo = 'yasunori-kirin0418/lightline_skk.vim'
depends = ['itchyny/lightline.vim', 'vim-skk/skkeleton']

[[plugins]]
repo = 'sineto/lightline-hunks'
depends = ['airblade/vim-gitgutter', 'sinetoami/lightline-hunks']

[[plugins]]
repo = 'gkeep/iceberg-dark'
depends = ['itchyny/lightline.vim']
hook_add = '''
let g:lightline.colorscheme = 'icebergDark'
'''

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(exe|so|dll)$',
    \ }
nnoremap <Leader>pb :<C-u>CtrlPBuffer<CR>
nnoremap <Leader>pf :<C-u>CtrlPBuffer<CR>
nnoremap <Leader>pm :<C-u>CtrlPMRU<CR>
'''

[[plugins]]
repo = 'mattn/ctrlp-ghq'
hook_add = '''
let g:ctrlp_ghq_actions = [
\ {"label": "Open", "action": "e", "path": 1},
\ {"label": "Look", "action": "!ghq look", "path": 0},
\]
nnoremap <Leader>pg :<C-u>CtrlPGhq<CR>
'''

[[plugins]]
repo = 'mattn/ctrlp-lsp'
hook_add = '''
nnoremap <Leader>ps :<C-u>CtrlPLspDocumentSymbol<CR>
'''

[[plugins]]
repo = 'mattn/vim-makedir-for'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nanotee/zoxide.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['rbgrouleff/bclose.vim']
hook_add = '''
nnoremap <Leader>tg :<C-u>TigGrep<CR>
nnoremap <Leader>tb :<C-u>TigBlame<CR>
nnoremap <Leader>ts :<C-u>TigStatus<CR>
nnoremap <Leader>tr :<C-u>TigOpenProjectRootDir<CR>
nnoremap <Leader>tf :<C-u>TigOpenCurrentFile<CR>
nnoremap <Leader>tc :<C-u>TigOpenFileWithCommit<CR>
'''

#[[plugins]]
#repo = 'iberianpig/ranger-explorer.vim'
#depends = ['rbgrouleff/bclose.vim']

[[plugins]]
repo = 'voldikss/vim-floaterm'

[[plugins]]
repo = 'ptzz/lf.vim'
depends = ['voldikss/vim-floaterm']
hook_add = '''
let g:lf_replace_netrw = 1
let g:lf_command_override = 'lf -command "set hidden"'
nnoremap <Leader>fc :Lflcd<CR>
'''

[[plugins]]
repo = 'mattn/vim-goimports'
hook_add = '''
let g:goimports = 1
let g:goimports_simplify = 1
let g:goimports_simplify_cmd = 'gofumpt'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key = '<C-y>'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'mattn/vim-findroot'

[[plugins]]
repo = 'mhinz/vim-sayonara'

[[plugins]]
repo = 'mattn/vim-gorename'

