[[plugins]]
hook_source = 'call denops#server#start()'
on_func = 'denops#server#start'
repo = 'vim-denops/denops.vim'

[[plugins]]
depends = ['vim-denops/denops.vim']
repo = 'lambdalisue/guise.vim'

[[plugins]]
depends = ['vim-denops/denops.vim']
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
depends = ['vim-denops/denops.vim']
hook_add = '''
source $HOME/.config/nvim/skkeletonrc.vim
'''
repo = 'vim-skk/skkeleton'

[[plugins]]
depends = ['vim-denops/denops.vim']
repo = 'kat0h/bufpreview.vim'

# [[plugins]]
# repo = 'skanehira/denops-gh.vim'

[[plugins]]
repo = 'skanehira/denops-germanium.vim'

[[plugins]]
depends = 'vim-denops/denops.vim'
on_event = 'InsertEnter'
repo = 'Shougo/ddc.vim'
#hook_source = '''
#execute 'source' fnamemodify($MYVIMRC, ':h'). '/ddcrc.vim'
#'''

[[plugins]]
depends = 'vim-lsp'
on_source = 'ddc.vim'
repo = 'shun/ddc-vim-lsp'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Omochice/dps-paiza-io-vim'
