[[plugins]]
hook_add = '''
augroup vimrc
    au!
    autocmd BufWritePre *.ts,*.tsx LspDocumentFormat
    autocmd BufWritePre *.js,*.jsx LspDocumentFormat
    autocmd BufWritePre *.json LspDocumentFormat
    autocmd BufWritePre *.cs LspDocumentFormat
    autocmd BufWritePre *.ps1 LspDocumentFormat
    autocmd BufWritePre *.go LspDocumentFormat
    autocmd BufWritePre *.fs LspDocumentFormat
    autocmd BufWritePre *.html,*.css LspDocumentFormat
    autocmd BufWritePre *.json,*.toml,*.yaml LspDocumentFormat
augroup END

highlight link LspErrorHighlight ALEErrorSign
highlight link LspWarningHighlight ALEWarningSign
highlight link LspErrorVirtualText Comment
highlight link LspWarningVirtualText Comment

let g:lsp_diagnostics_virtual_text_prefix = "▶ "
let g:lsp_diagnostics_signs_error = {'text': ''}
let g:lsp_diagnostics_signs_warning = {'text': ''}
let g:lsp_diagnostics_signs_hint = {'text': ''}

command! LspEnable call lsp#enable()
command! LspDisable call lsp#disable()
command! LspRestart call lsp#disable() | call lsp#enable()

nnoremap <Leader>lh <plug>(lsp-hover)
nnoremap <Leader>ld <plug>(lsp-definition)
nnoremap <Leader>lr <plug>(lsp-rename)
nnoremap <Leader>lf <plug>(lsp-document-format)
nnoremap <Leader>ls <plug>(lsp-status)
'''
on_func = 'lsp#enable'
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
hook_add = '''
let g:markdown_fenced_languages = ['ts=typescript']
let g:lsp_settings_filetype_typescript = ['typescript-language-server', 'eslint-language-server', 'deno']
let g:lsp_settings_filetype_go = ['gopls', 'golangci-lint-langserver']
'''
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'halkn/lightline-lsp'
