[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_func = 'lsp#enable'
hook_add = '''
augroup vimrc
    au!
    autocmd BufWritePre *.ts,*.tsx LspDocumentFormatSync
    autocmd BufWritePre *.js,*.jsx LspDocumentFormatSync
    autocmd BufWritePre *.json LspDocumentFormatSync
    autocmd BufWritePre *.cs LspDocumentFormatSync
    autocmd BufWritePre *.ps1 LspDocumentFormatSync
augroup END

highlight link LspErrorHighlight ALEErrorSign
highlight link LspWarningHighlight ALEWarningSign
highlight link LspErrorVirtualText Comment
highlight link LspWarningVirtualText Comment

let g:lsp_diagnostics_virtual_text_prefix = "▶ "
let g:lsp_diagnostics_signs_error = {'text': ''}
let g:lsp_diagnostics_signs_warning = {'text': ''}
let g:lsp_diagnostics_signs_hint = {'text': ''}

command! LspEnable call lsp#enable()
command! LspDisable call lsp#disable()()

nnoremap <Leader>lh <plug>(lsp-hover)
nnoremap <Leader>ld <plug>(lsp-definition)
nnoremap <Leader>lr <plug>(lsp-rename)
nnoremap <Leader>lf <plug>(lsp-document-format)
nnoremap <Leader>ls <plug>(lsp-status)
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:markdown_fenced_languages = ['ts=typescript']
let g:lsp_settings_filetype_typescript = ['typescript-language-server', 'eslint-language-server', 'deno']
let g:lsp_settings_filetype_go = ['gopls', 'golangci-lint-langserver']
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'halkn/lightline-lsp'
