icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2d3043"
idle_fg = "#c6c8d1"
alternating_tint_bg = "#161821"
alternating_tint_fg = "#c6c8d1"
critical_bg = "#1d2031"
critical_fg = "#e27878"
good_bg = "#2e3244"
good_fg = "#b4be82"
info_bg = "#161821"
info_fg = "#84a0c6"
separator_bg = "#161821"
separator_fg = "#c6c8d1"
separator = ""
warning_bg = "#1d2031"
warning_fg = "#e2a478"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "none"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "battery"
format = "{percentage} {time} {power}"
interval = 60

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
