format = """
[┌── ](bold white)$shell$time$directory$git_branch$git_status$go$python$cmd_duration
[└─](bold white)$character"""

scan_timeout = 10

[character]
success_symbol = "[❯❯❯](bold white) "
error_symbol =   "[❯❯❯](bold red) "

[shell]
disabled = false
format = "${indicator}"
fish_indicator = "><>"
powershell_indicator = ">_"
zsh_indicator = "[z]"
bash_indicator = "$_"
unknown_indicator = "[?]"

[directory]
style = "bold blue"
read_only_style = "blue"
fish_style_pwd_dir_length = 3
format = "[$read_only]($read_only_style)[  ]($style)[$path]($style) "
truncation_length = 8 
truncation_symbol = ".../"

[git_status]
conflicted = " "
untracked  = "?"
stashed    = "$"
modified   = " "
staged     = " "
renamed    = " "
deleted    = "✘ "
style = "bold yellow"
ahead = "▲ ${count}"
behind = "▼ ${count}"
diverged = "♦ ▲ ${ahead_count} ▼ ${behind_count}"

[cmd_duration]
format = "took [$duration](bold white)"

[time]
disabled = true
format = '[\[$time\]](bold white) '
time_format = "%T"
utc_time_offset = "+9"

[status]
style = "red"
symbol = "✖"
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "⚡"
signal_symbol = "⚡"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
