[[plugins]]
repo = 'sheepla/mayano.vim'

#[[plugins]]
#repo = 'mattn/vim-sl'

# [[plugins]]
# repo = 'mattn/die-vim'

[[plugins]]
repo = 'unkontributors/super_unko.vim'

#[[plugins]]
#repo = 'skanehira/christmas.vim'
